server:
  port: 8000
  servlet:
    context-path:

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 18000
      max-lifetime: 30000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaofu?useUnicode=true&useAffectedRows=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*xml

---
spring:
  profiles: dev

---
spring:
  profiles: staging

---
spring:
  profiles: prod